### ISSUE TITLE
ループブロック内に動作ブロックが無いときのバグ

### ISSUE THREAD

**Issue by Dai1678** [t-robop/00-Atlas-ac#133]
以下の2例で IndexOutOfBoundsException が発生してクラッシュ

![screenshot_20180728-235026](https://user-images.githubusercontent.com/19250035/43357764-7d9b3050-92c1-11e8-9781-64c439337b0d.png)
↑ループブロックのみで、内部に動作ブロックが無い時  

![screenshot_20180728-235038](https://user-images.githubusercontent.com/19250035/43357774-a216bdbe-92c1-11e8-88e3-1dda102a8eb0.png)
↑内部に動作ブロックが無いループブロックのあとに、動作ブロックが続く時  

以下の2例ではクラッシュは起きなかった。

![screenshot_20180728-235052](https://user-images.githubusercontent.com/19250035/43357792-dcbb77ac-92c1-11e8-874f-44143f02a02e.png)
↑内部に動作ブロックが無いループブロックの前に、動作ブロックが続いている時  

![screenshot_20180728-235045](https://user-images.githubusercontent.com/19250035/43357810-03a8548e-92c2-11e8-9e58-91886f7949ac.png)
↑内部に動作ブロックがないループブロックの前後に、動作ブロックが続いている時

**Comment by Dai1678** [comment]
上記画像のエラー１例目についてのエラーメッセージ抜粋

07-28 23:59:25.888 25715-25715/com.robop.scriptrobotcontroller E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.robop.scriptrobotcontroller, PID: 25715
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.robop.scriptrobotcontroller.MainActivity.convertLoopItem(MainActivity.java:523)
        at com.robop.scriptrobotcontroller.MainActivity.evolutionItems(MainActivity.java:511)
        at com.robop.scriptrobotcontroller.MainActivity.getForDeployed(MainActivity.java:446)
        at com.robop.scriptrobotcontroller.MainActivity.onClick(MainActivity.java:318)

**Comment by Dai1678** [comment]
MainActivity.java:523
->

if (items.get(i).getBlockState() == 2) {

**Comment by TaigaNatto** [comment]
普通に整形間違えてるだけだからデバッグモードで頑張って解決してほしい

**Comment by Dai1678** [comment]
善処しました(わからないの意)
